name = "Minimal Tony"
license = "MIT"
licenselink = "https://github.com/yourusername/minimal-tony/blob/master/LICENSE"
description = "A minimal, black and white theme with dark/light mode toggle, designed with assistance from Claude by Anthropic"
homepage = "https://tonycoppola.net/"
tags = ["blog", "minimal", "responsive", "dark mode", "light mode"]
features = ["blog", "responsive", "dark mode"]
min_version = "0.41.0"

[author]
  name = "Tony Coppola"
  homepage = "https://tonycoppola.net"